# Generated by Django 3.1.5 on 2021-01-21 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('text', models.TextField()),
                ('has_link', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('total_likes', models.IntegerField()),
                ('total_retweets', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tip')),
            ],
        ),
    ]
