# Generated by Django 3.1.5 on 2021-01-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
