# Generated by Django 3.1.5 on 2021-01-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
