# Generated by Django 3.1.5 on 2021-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_twitteruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='author',
            new_name='author_name',
        ),
        migrations.AddField(
            model_name='tip',
            name='author_email',
            field=models.EmailField(default='pythontip@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
